### ISSUE TITLE
New Announcement on Homepage

### ISSUE THREAD

**Issue by towellclaire** [Scorpio750/deep-treble-redesign#5]
- Text: "Come to our FREE Valentine's Day concert this Friday! 
{insert clickable image below this caption}
- subtext: Click the image for more details {subtext is below photo in a smaller font}
- Link to event: https://www.facebook.com/events/1212025628881386/ 
- Make this the standard Layout for all announcements on homepage!
![jessie](https://cloud.githubusercontent.com/assets/25470234/22671752/eb6019d2-ec9d-11e6-9638-818a5010908e.png)

**Comment by Scorpio750** [comment]
So Github didn't send any email notifs (need to check on that), and I totally forgot about this in the mayhem that is my work, completely my bad. In the future please let me know in chat as well when deadlines are coming up.

@towellclaire any suggestions for replacement banner image post-concert?
